insert into public.recipe_instruction (id, details, step, recipe_id)
values  (42, 'Rinse quinoa thoroughly in a fine-mesh sieve until the water runs clear.', 1, 15),
        (3, 'Spread the mashed avocado on the toast. Season with salt and pepper.', 2, 1),
        (2, 'Toast the bread in the toaster or in a non-stick frying pan. Cut the avocado all the way around the stone. Twist the two halves apart. Remove the stone and scoop the flesh out of the skin. Finely mash the flesh.', 1, 1),
        (4, 'Beat the eggs with 1 tablespoon of water in a mixing bowl. Heat a non-stick frying pan on a high heat. Add the butter in the pan to melt. Lower the heat slightly and add the beaten eggs. ', 3, 1),
        (7, 'Stir with a spatula until the eggs are almost firm but still a little runny. Divide the scrambled eggs over the avocado. Season with salt and pepper.', 4, 1),
        (43, 'In a medium saucepan, combine rinsed quinoa, water, and a pinch of salt. Bring to a boil over high heat, then reduce heat to low, cover, and simmer for 15 minutes, or until quinoa is cooked through and fluffy.', 2, 15),
        (44, 'While quinoa is cooking, prepare the grilled vegetables. Preheat grill to medium-high heat. Cut your preferred vegetables (such as zucchini, bell peppers, onions, and mushrooms) into bite-sized pieces. Toss vegetables with olive oil, salt, and pepper.', 3, 15),
        (5, 'Preheat an oven to 450 degrees F (230 degrees C).', 1, 2),
        (21, 'Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch.', 2, 2),
        (22, 'Season chicken thoroughly with salt and pepper. Using a sifter or strainer; sprinkle flour over chicken breasts, evenly coating both sides', 3, 2),
        (23, 'Beat eggs in a shallow bowl and set aside.', 4, 2),
        (24, 'Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside.', 5, 2),
        (25, 'Dip a flour-coated chicken breast in beaten eggs. Transfer breast to the bread crumb mixture, pressing crumbs into both sides. Repeat for each breast. Let chicken rest for 10 to 15 minutes.', 6, 2),
        (26, 'Heat 1/2 inch olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken in the hot oil until golden, about 2 minutes per side. The chicken will finish cooking in the oven.', 7, 2),
        (27, 'Transfer chicken to a baking dish. Top each breast with 2 tablespoons tomato sauce. ', 8, 2),
        (28, 'Layer each chicken breast with equal amounts of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle remaining Parmesan over top and drizzle each with 1/2 teaspoon olive oil.', 9, 2),
        (29, 'Bake in the preheated oven until cheese is browned and bubbly and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).', 10, 2),
        (6, 'In a mixing bowl, whisk together the broccoli salad dressing ingredients (if you like to multi-task, do it while the bacon is cooking).', 1, 3),
        (30, 'Then sauté the bacon in a skillet until browned and crisp. Don’t forget to toss it occasionally.', 2, 3),
        (31, 'Add the remaining salad ingredients (broccoli, cauliflower, red onion, cheddar) and cooled bacon to a salad bowl.', 3, 3),
        (32, 'Pour that creamy dressing over the top and toss to evenly coat. Easy as that!
', 4, 3),
        (33, 'Preheat the oven to 350 degrees F (175 degrees C). Coat the bottom of a glass or nonstick baking dish with olive oil, just enough to coat.', 1, 4),
        (34, 'Wash and peel sweet potatoes; cut into medium pieces.Place in the baking dish and stir to coat with olive oil. Sprinkle with oregano, salt, and pepper.

', 2, 4),
        (35, 'Bake in the preheated oven until soft and fork-tender, about 45 minutes to 1 hour.', 3, 4),
        (36, 'Preheat your grill to medium-high heat.', 1, 6),
        (37, 'Rinse the quinoa under cold water and drain.', 2, 6),
        (38, 'In a medium saucepan, bring 2 cups of water to a boil. Add the quinoa, reduce heat to low, cover, and simmer for about 15 minutes, or until all water is absorbed. Remove from heat and let it sit covered for 5 minutes.', 3, 6),
        (39, 'While the quinoa is cooking, steam the broccoli florets until tender but still crisp, about 3-4 minutes.', 4, 6),
        (40, 'Brush the salmon fillets with olive oil and season with salt and pepper. Place the salmon on the grill and cook for about 4-5 minutes on each side, or until desired doneness.', 5, 6),
        (41, 'Divide the quinoa and steamed broccoli between plates.Garnish with lemon wedges and serve immediately.
', 6, 6),
        (45, 'Grill prepared vegetables for 5-7 minutes per side, or until tender and slightly charred.', 4, 15),
        (46, 'Once quinoa is cooked, fluff it with a fork and let it cool slightly.', 5, 15),
        (47, 'In a large bowl, combine cooked quinoa, grilled vegetables, and your favorite salad dressing.', 6, 15),
        (48, 'Gently toss to coat all ingredients evenly.', 7, 15),
        (49, 'Taste and adjust seasonings as desired.', 8, 15),
        (50, 'Serve immediately and enjoy your flavorful and nutritious quinoa salad!', 9, 15),
        (51, 'Rinse and chop mushrooms.', 1, 16),
        (52, 'Melt butter or heat olive oil in a large saucepan over medium heat.', 2, 16),
        (53, 'Add chopped mushrooms to the pan and sauté until softened and browned, about 5-7 minutes.', 3, 16),
        (54, 'Stir in minced garlic and cook for 30 seconds more, until fragrant.', 4, 16),
        (55, 'Sprinkle with all-purpose flour and whisk to coat the mushrooms evenly.', 5, 16),
        (56, 'Gradually whisk in chicken broth or vegetable broth, stirring constantly to prevent lumps.', 6, 16),
        (57, 'Bring to a simmer and cook for 10 minutes, or until mushrooms are tender and flavors have melded.', 7, 16),
        (58, 'Remove from heat and let the soup cool slightly.', 8, 16),
        (59, 'Using an immersion blender or regular blender, puree the soup until smooth and creamy.', 9, 16),
        (60, 'Stir in milk or cream (optional) for a richer flavor.', 10, 16),
        (61, 'Season with salt, pepper, and a pinch of nutmeg to taste.', 11, 16),
        (62, 'Garnish with fresh herbs like parsley or thyme, if desired.', 12, 16),
        (63, 'Serve warm with crusty bread for a comforting and satisfying meal.', 13, 16),
        (64, 'Preheat oven to 400°F (200°C).', 1, 17),
        (65, 'In a small bowl, whisk together olive oil, lemon juice, rosemary leaves, salt, and pepper.', 2, 17),
        (66, 'Pat chicken dry with paper towels and place it in a roasting pan.', 3, 17),
        (67, 'Pour the prepared marinade over the chicken, ensuring it is evenly coated.', 4, 17),
        (68, 'Using your hands, gently massage the marinade into the chicken skin.', 5, 17),
        (69, 'Place quartered potatoes or other root vegetables around the chicken in the roasting pan.', 6, 17),
        (70, 'Roast for 20-25 minutes, or until chicken is cooked through and golden brown, and vegetables are tender.', 7, 17),
        (71, 'Remove from the oven and let to rest 5 mins', 7, 17),
        (72, 'Gather your ingredients: spinach leaves, banana, plant-based milk, almonds, and protein powder (optional).', 1, 18),
        (73, 'Rinse and chop the spinach leaves if not using pre-chopped spinach.', 2, 18),
        (74, 'Peel and slice the banana.', 3, 18),
        (75, 'Add all ingredients (spinach, banana, milk, almonds, and optional protein powder) to a blender.', 4, 18),
        (76, 'Blend on high speed for 30-60 seconds, or until smooth and creamy.', 5, 18),
        (77, 'Pour the smoothie into a glass and enjoy it immediately for maximum freshness and nutrients!', 6, 18),
        (78, 'Pat your preferred fish fillet (such as salmon, cod, or tilapia) dry with paper towels.', 1, 19),
        (79, 'Season the fish with salt, pepper, and any other desired spices.', 2, 19),
        (80, 'Preheat your grill to medium-high heat.', 3, 19),
        (81, 'Lightly oil the grill grates to prevent sticking.', 4, 19),
        (82, 'Grill the fish for 4-5 minutes per side, or until cooked through and flaky.', 5, 19),
        (83, 'While the fish is cooking, prepare your salad. Wash and chop your preferred salad greens and vegetables (such as lettuce, tomatoes, cucumbers, and onions).', 6, 19),
        (84, 'Spread a thin layer of dressing on a whole wheat tortilla.', 7, 19),
        (85, 'Layer the salad greens and vegetables on top of the dressing.', 8, 19),
        (86, 'Once cooked, place the fish fillet on top of the salad in the wrap.', 9, 19),
        (87, 'Roll up the tortilla tightly to enclose the filling.', 10, 19),
        (88, 'Cut the wrap in half and enjoy a delicious and healthy lunch!', 11, 19),
        (89, 'Rinse lentils under cold running water until the water runs clear.', 1, 20),
        (90, 'In a large pot, heat olive oil over medium heat.', 2, 20),
        (91, 'Add chopped onions and carrots to the pot and sauté until softened, about 5 minutes.', 3, 20),
        (92, 'Stir in chopped garlic and cook for an additional minute until fragrant.', 4, 20),
        (93, 'Add rinsed lentils, vegetable broth, and your favorite spices (such as cumin, coriander, and turmeric).', 5, 20),
        (94, 'Bring to a boil, then reduce heat to low, cover, and simmer for 20-25 minutes, or until lentils are tender.', 6, 20),
        (95, 'Stir in chopped tomatoes (optional) and simmer for an additional 5 minutes.', 7, 20),
        (96, 'Season with salt and pepper to taste.', 8, 20),
        (97, 'Serve hot with crusty bread for a hearty and comforting meal.', 9, 20),
        (98, 'Preheat oven to 400°F (200°C).', 1, 21),
        (99, 'Pat salmon fillets dry with paper towels.', 2, 21),
        (100, 'Season the salmon with salt, pepper, and any other desired spices (e.g., paprika, garlic powder).', 3, 21),
        (101, 'Prepare your chosen vegetables for roasting. Cut vegetables like broccoli, Brussels sprouts, asparagus, or bell peppers into bite-sized pieces.', 4, 21),
        (102, 'Toss the vegetables with olive oil, salt, and pepper.', 5, 21),
        (103, 'Spread the prepared vegetables on a baking sheet.', 6, 21),
        (104, 'Place the seasoned salmon fillets on top of the vegetables on the baking sheet.', 7, 21),
        (105, 'Bake for 15-20 minutes, or until the salmon is cooked through and flaky and the vegetables are tender-crisp.', 8, 21),
        (106, 'Serve immediately with lemon wedges and your favorite dipping sauce (optional).', 9, 21),
        (107, 'Cook whole wheat pasta according to package instructions in a large pot of salted boiling water.', 1, 22),
        (108, 'While the pasta is cooking, prepare the pesto. If using store-bought pesto, simply open the jar.', 2, 22),
        (109, 'For homemade pesto, blend together fresh basil leaves, pine nuts, garlic, olive oil, and Parmesan cheese in a food processor until a smooth sauce forms.', 3, 22),
        (110, 'Reserve about ½ cup of pasta water before draining the pasta.', 4, 22),
        (111, 'Drain the cooked pasta and return it to the pot.', 5, 22),
        (112, 'Add the pesto, sun-dried tomatoes (chopped), and a splash of reserved pasta water to the pot.', 6, 22),
        (113, 'Toss everything together until well combined and the sauce coats the pasta evenly. Add more pasta water if needed to achieve desired consistency.', 7, 22),
        (114, 'Season with salt and pepper to taste.', 8, 22),
        (115, 'Serve hot with grated Parmesan cheese (optional) and enjoy a flavorful and vegetarian pasta dish!', 9, 22),
        (116, 'Rinse quinoa thoroughly under cold running water until the water runs clear.', 1, 23),
        (117, 'Cook quinoa according to package instructions in a pot with water or vegetable broth.', 2, 23),
        (118, 'While the quinoa cooks, prepare the vegetables. Grate or finely chop carrots, zucchini, and onion.', 3, 23),
        (119, 'In a large bowl, combine cooked quinoa, grated/chopped vegetables, mashed chickpeas (optional for added protein and texture), and your favorite spices (e.g., cumin, coriander, smoked paprika).', 4, 23),
        (120, 'Mix well and form the mixture into patties using your hands.', 5, 23),
        (121, 'Heat a pan or grill over medium heat with a drizzle of olive oil.', 6, 23),
        (122, 'Cook the quinoa burgers for 3-4 minutes per side, or until golden brown and crispy on the outside and cooked through on the inside.', 7, 23),
        (123, 'Serve the vegetarian quinoa burgers on hamburger buns with your favorite toppings (e.g., lettuce, tomato, avocado, vegan mayo).', 8, 23),
        (124, 'Rinse brown rice thoroughly under cold running water.', 1, 24),
        (125, 'Cook brown rice according to package instructions in a pot with water or vegetable broth.', 2, 24),
        (126, 'While the rice cooks, prepare the tofu. Drain and press extra-firm tofu to remove excess moisture.', 3, 24),
        (127, 'Cut the tofu into bite-sized cubes.', 4, 24),
        (128, 'In a small bowl, combine soy sauce, rice vinegar, sesame oil, a pinch of cornstarch (optional for thickening), and a touch of honey or maple syrup for balance.', 5, 24),
        (129, 'Heat a large skillet or wok over medium-high heat with a drizzle of oil (vegetable oil, peanut oil, etc.).', 6, 24),
        (130, 'Add the tofu cubes to the hot skillet and stir-fry for 5-7 minutes, or until golden brown and crispy on all sides.', 7, 24),
        (131, 'Add your favorite stir-fry vegetables (e.g., broccoli florets, shredded carrots, sliced bell peppers) to the pan and cook for an additional 3-5 minutes, or until tender-crisp.', 8, 24),
        (132, 'Pour the prepared sauce over the tofu and vegetables in the pan.', 9, 24),
        (133, 'Toss gently to coat the ingredients evenly with the sauce.', 10, 24),
        (134, 'Continue cooking for another minute or two, until the sauce thickens slightly and coats the ingredients.', 11, 24),
        (135, 'Fluff the cooked brown rice with a fork and divide it among serving bowls.', 12, 24),
        (136, 'Top each bowl of rice with the stir-fried tofu and vegetables.', 13, 24),
        (137, 'Garnish with chopped green onions, sesame seeds, or other desired toppings.', 14, 24),
        (138, 'Serve immediately and enjoy your customizable and flavorful brown rice bowl!', 15, 24),
        (139, 'Rinse quinoa thoroughly under cold running water until the water runs clear.', 1, 7),
        (140, 'In a medium saucepan, combine rinsed quinoa, water, and a pinch of salt. Bring to a boil over high heat, then reduce heat to low, cover, and simmer for 15 minutes, or until quinoa is cooked through and fluffy.', 2, 7),
        (141, 'While quinoa is cooking, prepare the other salad ingredients. Cut cucumbers, tomatoes, red onion, and Kalamata olives into bite-sized pieces.', 3, 7),
        (142, 'In a large bowl, combine cooked quinoa, chopped vegetables, crumbled feta cheese, and chopped fresh parsley.', 4, 7),
        (143, 'For the dressing, whisk together olive oil, lemon juice, oregano, salt, and pepper.', 5, 7),
        (144, 'Pour the dressing over the salad and toss gently to coat all ingredients evenly.', 6, 7),
        (145, 'Taste and adjust seasonings as desired.', 7, 7),
        (146, 'Serve immediately and enjoy a refreshing and flavorful Mediterranean quinoa salad!', 8, 7),
        (147, 'Preheat oven to 400°F (200°C).', 1, 8),
        (148, 'Cut the tops off of bell peppers and remove seeds and membranes.', 2, 8),
        (149, 'In a large bowl, combine cooked rice, cooked ground beef or turkey, chopped onions, chopped tomatoes, and your favorite spices (e.g., cumin, chili powder, oregano).', 3, 8),
        (150, 'Stuff the pepper halves with the prepared mixture.', 4, 8),
        (151, 'Place the stuffed peppers in a baking dish.', 5, 8),
        (152, 'Pour a small amount of water or vegetable broth into the bottom of the baking dish to prevent the peppers from drying out.', 6, 8),
        (153, 'Cover the baking dish with aluminum foil.', 7, 8),
        (154, 'Bake for 30-40 minutes, or until the peppers are tender and the filling is heated through.', 8, 8),
        (155, 'Remove the foil and bake for an additional 5-10 minutes, or until the tops of the peppers are slightly browned.', 9, 8),
        (156, 'Serve hot with a dollop of sour cream or plain yogurt (optional).', 10, 8),
        (157, 'Cut chicken breasts into bite-sized pieces.', 1, 9),
        (158, 'Marinate the chicken in a mixture of soy sauce, rice vinegar, sesame oil, and cornstarch (optional) for at least 30 minutes, or up to overnight.', 2, 9),
        (159, 'Heat a large skillet or wok over medium-high heat with a drizzle of oil (vegetable oil, peanut oil, etc.).', 3, 9),
        (160, 'Add the marinated chicken to the hot pan and stir-fry for 5-7 minutes, or until cooked through and no longer pink.', 4, 9),
        (161, 'Remove the chicken from the pan and set aside.', 5, 9),
        (162, 'Add your favorite stir-fry vegetables (e.g., broccoli florets, shredded carrots, sliced bell peppers) to the pan and cook for 3-5 minutes, or until tender-crisp.', 6, 9),
        (163, 'Pour the prepared stir-fry sauce (see below) into the pan with the vegetables.', 7, 9),
        (164, 'Bring the sauce to a simmer and cook for 1-2 minutes, or until it thickens slightly.', 8, 9),
        (165, 'Return the cooked chicken to the pan and toss with the vegetables and sauce.', 9, 9),
        (166, 'Serve immediately over cooked rice or noodles, and enjoy your delicious chicken stir-fry!', 10, 9),
        (167, 'Gather your favorite frozen berries (e.g., strawberries, blueberries, raspberries, blackberries).', 1, 10),
        (168, 'If using fresh berries, freeze them for at least a few hours before using.', 2, 10),
        (169, 'In a blender, combine frozen berries, yogurt (plain or flavored), a splash of milk or plant-based milk, and a touch of honey or maple syrup (optional) for sweetness.', 3, 10),
        (170, 'Blend until smooth and creamy, adding more milk or yogurt if needed to achieve desired consistency.', 4, 10),
        (171, 'Pour the smoothie into a bowl and top with your favorite garnishes (e.g., granola, chopped nuts, fresh fruit slices, shredded coconut).', 5, 10),
        (172, 'Enjoy your refreshing and nutritious berry smoothie bowl!', 6, 10),
        (173, 'Separate the egg yolks from the egg whites. Reserve the egg whites for another use or discard them.', 1, 11),
        (174, 'In a small bowl, whisk together egg yolks, grated Parmesan cheese, and a pinch of salt and pepper.', 2, 11),
        (175, 'Cook spaghetti according to package instructions in a large pot of salted boiling water.', 3, 11),
        (176, 'While the spaghetti is cooking, heat a large skillet over medium heat with a drizzle of olive oil.', 4, 11),
        (177, 'Add chopped pancetta or bacon to the skillet and cook until crispy.', 5, 11),
        (178, 'Using a slotted spoon, remove the cooked pancetta/bacon from the skillet, reserving some of the drippings for extra flavor.', 6, 11),
        (179, 'Reserve about ½ cup of pasta water before draining the cooked spaghetti.', 7, 11),
        (180, 'Drain the spaghetti and immediately transfer it to the hot skillet with the reserved pancetta drippings.', 8, 11),
        (181, 'Toss the spaghetti with the pancetta/bacon drippings, then remove the pan from the heat.', 9, 11),
        (182, 'Slowly whisk the egg yolk mixture into the hot pasta, along with a splash of reserved pasta water, to create a creamy sauce.', 10, 11),
        (183, 'Continue tossing and adding pasta water until the sauce coats the pasta evenly and has a slightly thickened consistency.', 11, 11),
        (184, 'Season with additional salt and pepper to taste.', 12, 11),
        (185, 'Stir in the cooked pancetta/bacon and grated Parmesan cheese.', 13, 11),
        (186, 'Serve immediately, garnished with fresh parsley (optional), and enjoy a classic Italian Spaghetti Carbonara!', 14, 11),
        (187, 'In a large bowl, combine chopped tomatoes, cucumbers, red onion, crumbled feta cheese, and Kalamata olives.', 1, 12),
        (188, 'For the dressing, whisk together olive oil, lemon juice, oregano, salt, and pepper.', 2, 12),
        (189, 'Pour the dressing over the salad and toss gently to coat all ingredients evenly.', 3, 12),
        (190, 'Add sliced bell peppers, artichoke hearts, or other desired chopped vegetables for more variation.', 4, 12),
        (191, 'Garnish with chopped fresh parsley or mint (optional).', 5, 12),
        (192, 'Serve immediately and enjoy your refreshing and flavorful Greek salad!', 6, 12),
        (193, 'Drain canned tuna in water or olive oil. Flake the tuna with a fork, discarding any large bones or cartilage.', 1, 13),
        (194, 'In a medium bowl, combine the flaked tuna with mayonnaise, chopped celery (optional for added crunch), and a squeeze of lemon juice (optional for added brightness).', 2, 13),
        (195, 'Season the tuna salad with salt and pepper to taste.', 3, 13),
        (196, 'Choose your favorite bread for the sandwich (e.g., whole wheat, sourdough, rye). Toast the bread slices if desired.', 4, 13),
        (197, 'Spread a layer of prepared tuna salad on one slice of bread.', 5, 13),
        (198, 'Add your favorite toppings to the sandwich (e.g., lettuce, tomato, sliced onion, avocado).', 6, 13),
        (199, 'Top with the other slice of bread and cut the sandwich in half (optional).', 7, 13),
        (200, 'Serve immediately and enjoy your delicious and customizable tuna salad sandwich!', 8, 13),
        (201, 'Tip half the raspberries and all of the orange juice in a pan. Simmer until the raspberries soften, about 5 mins.', 1, 25),
        (202, 'Meanwhile stir the oats, milk and 450ml water in a pan over a low heat until creamy. Top with the raspberry compote, remaining raspberries, orange slices, banana, almond butter, goji berries and chia seeds.', 2, 25),
        (203, 'Make waffles: Fit wire rack inside rimmed baking sheet and heat oven to 225°F. ', 1, 26),
        (204, 'In medium bowl or measuring cup, whisk together milk, egg, and vegetable oil until smooth.', 2, 26),
        (205, 'In large bowl, whisk together flour, sugar, baking powder, baking soda, and salt; make well in center and gradually whisk in milk mixture until mostly smooth (some small lumps are OK). Fold in Parmesan.', 3, 26),
        (206, 'Adjust waffle maker to make thin (unstuffed) waffles and heat until green ready light turns on, about 3 minutes (or use other waffle maker and follow manufacturer’s directions).', 4, 26),
        (207, 'Lightly brush vegetable oil on upp and low plates of wafflemaker. Add 1/4 cup batter to center of machine close lid and use handle to flip waffle maker over to other side; cook until green light reappears, 2 to 3 minutes (3 minutes for crispier waffles).', 5, 26),
        (208, 'Transfer waffle to prepared rack and keep warm in oven. Repeat with remaining batter, brushing with additional vegetable oil only if necessary.', 6, 26),
        (209, 'Meanwhile, make topping: Using electric mixer, beat ricotta on medium, adding milk if needed, until light and fluffy, 2 to 3 minutes. Mix in lemon zest and chopped mint. Taste and season with 1/8 teaspoon salt if needed.', 7, 26),
        (210, 'In medium bowl, toss tomatoes with olive oil and a pinch each of salt and pepper, then remaining 2 tablespoons mint leaves (tear into smaller pieces if large)', 8, 26),
        (211, 'Serve waffles topped with ricotta as well as tomato mixture and sprinkled with additional mint and lemon zest if desired.', 9, 26),
        (212, 'Heat oven to 450°F. On rimmed baking sheet, toss tomatoes with 1 tablespoon oil, smoked paprika, and 1/2 teaspoon each salt and pepper. Roast until tomatoes start to release liquid and break down, 8 minutes. ', 1, 27),
        (213, 'Meanwhile, using mortar and pestle, crush coriander and cumin seeds until coarsely ground.', 2, 27),
        (214, 'When tomatoes are ready, sprinkle evenly with feta. Using back of spoon, create 8 wells (1 for each egg) in tomatoes, then sprinkle with ground coriander and cumin seeds. ', 3, 27),
        (215, 'Bake until cheese is slightly melted, 2 to 3 minutes. Crack 1 egg into each well and bake until egg whites are just set, 3 to 5 minutes more. Sprinkle with basil.', 4, 27),
        (283, 'Preheat oven to 400 F.', 1, 41),
        (216, 'Meanwhile, in large bowl, whisk lemon juice with remaining Tbsp oil. Add greens and 1/4 teaspoon each salt and pepper and toss to coat. Serve alongside baked eggs with toast.', 5, 27),
        (217, 'In a large bowl, whisk together eggs, 1 tablespoon water and 1/2 teaspoon each salt and pepper.', 1, 28),
        (218, 'Heat oil or butter in a 10-inch nonstick skillet on medium. Add eggs and cook, stirring with a rubber spatula every few seconds, to desired doneness, 2 to 3 minutes for medium-soft eggs.', 2, 28),
        (219, 'Fold crème fraîche, then trout and red onion into scrambled eggs. Dollop with additional crème fraîche.', 3, 28),
        (220, 'Heat oven to 375°F and lightly oil 9- by 13-inch baking dish. In large bowl, stir together oats, baking powder, cinnamon, nutmeg, salt and cloves.', 1, 29),
        (221, 'In second large bowl, whisk eggs until no streaks remain. Add applesauce, milk, maple syrup, ginger, vanilla and
6 tablespoons oil and whisk until combined.', 2, 29),
        (222, 'Add dry ingredients to bowl and stir until just combined. Reserve 1/3 cup chopped pecans for topping and fold remaining into batter along with apples.', 3, 29),
        (223, 'Spread batter in pan in even layer. Scatter reserved pecans on top and bake in top third of oven until fully set and edges begin to brown, 45 to 55 minutes. Let cool 10 minutes before serving.', 4, 29),
        (225, 'In large bowl, whisk together eggs, milk, everything bagel seasoning if filling with cream cheese, and 1/2 teaspoon each salt and pepper. ', 2, 30),
        (226, 'Divide half of egg mixture among prepared muffin cups, followed by desired fillings (except grated cheese) and then remaining egg mixture.', 3, 30),
        (227, 'Top with grated cheese if using and bake until puffed and set, 20 to 25 minutes. ', 4, 30),
        (224, 'Heat oven to 350°F. Coat 12-cup muffin pan with nonstick spray.', 1, 30),
        (228, 'Heat oven to 300°F. Line rimmed baking sheet with parchment paper. In medium bowl, whisk together oil, maple syrup and salt.', 1, 32),
        (229, 'Heat medium cast-iron skillet on medium-high. Add groats and toast, shaking and tossing often and adjusting heat as needed, until crisp and light golden brown, 2 to 4 minutes.', 2, 32),
        (230, 'Transfer to bowl with maple syrup mixture and toss to coat (it will sizzle), then stir in cinnamon and almonds.', 3, 32),
        (231, 'Spread mixture onto prepared baking sheet and bake, stirring
halfway through, until golden brown, 15 to 20 minutes. Let cool.', 4, 32),
        (232, 'Serve granola with yogurt, berries and drizzle of maple syrup if desired.
', 5, 32),
        (233, 'In medium bowl, smash avocado with lemon juice and 1/4 teaspoon each salt and pepper.', 1, 33),
        (234, 'Spread on toast and top with eggs and radishes and sprinkle with chives and sesame seeds. ', 2, 33),
        (235, 'In a medium mixing bowl, combine beef with pepper, soy sauce, cooking wine, cornstarch and oil until evenly coated. Set the beef aside, allowing it to marinate for at least 10 minutes.', 1, 34),
        (236, 'Heat oil in a large skillet over medium-high heat for 2 minutes until the hot oil sizzles. Add in the marinated beef and stir fry until nicely browned on all sides, about 3-4 minutes. ', 2, 34),
        (237, 'Add garlic and ginger. Sauté together until fragrant, about 1 minute. Transfer the beef mixture to a plate.', 3, 34),
        (238, 'In another bowl, whisk together all the sauce ingredients until the sugar and cornstarch is fully dissolved. Set aside.', 4, 34),
        (239, 'In the same skillet over medium-high heat, add the remaining 1 tablespoon oil, broccoli and the sauce mixture. ', 5, 34),
        (240, 'Cover the lid and let the broccoli simmer in the sauce until tender, about 2-3 minutes, stirring occasionally. The broccoli should be crunchy tender but still green.', 6, 34),
        (241, 'Return the beef to the skillet and stir well to combine. Cook for another minute until evenly coated with thickened sauce.', 7, 34),
        (242, 'Sprinkle sesame seeds on top and serve immediately with steamed rice.', 8, 34),
        (243, 'n a medium mixing bowl, combine the chicken, soy sauce, cooking wine, vinegar and cornstarch. Mix until the chicken is fully coated. ', 1, 35),
        (244, 'Place the chicken and marinade in ziploc bag and squeeze out all the air. Place the bag in the refrigerator and marinate for at least 1 hour. If you have time, let it marinate longer.', 2, 35),
        (245, 'Heat oil in a large non-stick frying pan or wok over medium high heat for 2 minutes until the hot oil sizzles and shimmers. ', 3, 35),
        (246, 'Add the chicken to the frying pan and stir fry continuously for about 7-10 minutes until the chicken is no longer pink inside.', 4, 35),
        (247, 'Add sugar and stir to coat the chicken for a minute. The melted sugar will caramelize the chicken, which makes it turn brown. ', 5, 35),
        (248, 'Add in lemon juice, lemon zest, honey and soy sauce. Stir well to combine and coat the chicken.', 6, 35),
        (249, 'In a small bowl, whisk to combine water and cornstarch. Pour in the cornstarch mixture and stir well until the sauce starts to thicken and forms into a smooth consistency.', 7, 35),
        (250, 'Mix evenly to coat chicken. Sprinkle sesame seeds and sliced green onions on top.', 8, 35),
        (251, 'Serve over a bowl of steamed rice and garnish with extra sesame seeds and lemon slices.', 9, 35),
        (252, 'Use a paper towel to pat the chicken completely dry. Cut the chicken into a 1.5-inch cubes, and set aside on a plate.', 1, 36),
        (253, 'Heat oil in a large skillet over medium-high heat until the hot oil sizzles, about 1 minute. Add chicken and sauté until golden brown on all sides, about 5-6 minutes. Drain the excess oil from the pan.', 2, 36),
        (254, 'In a small mixing bowl, whisk together soy sauce, sugar, ginger, garlic, sesame oil, rice vinegar, and cornstarch until smooth.', 3, 36),
        (255, 'Stir in the sauce mixture and toss well to coat the chicken evenly. Continue to cook over medium heat for 3-4 minutes until thickened to a desired consistency, stirring constantly.', 4, 36),
        (256, 'Garnish with sesame seeds and green onions and serve warm over a bowl of steamed rice, fried rice, or noodles.', 5, 36),
        (257, 'Soak the dry noodles in a large mixing bowl filled with hot water for 1 minute, or according to the package instructions. Drain well and set aside.', 1, 37),
        (258, 'Heat oil in a large skillet over medium-high heat until sizzling hot, about 1 minute. Add onion and sauté until fragrant, about 1 minute.', 2, 37),
        (259, 'Add carrot, bell pepper, bok choy, and broccoli, and cook until tender, about 2-3 minutes.', 3, 37),
        (260, 'Add cooked chicken and ginger. Use a spatula to mix well until evenly distributed.', 4, 37),
        (261, 'Stir in the soaked and drained noodles, and cook for 1 minute.', 5, 37),
        (262, 'Add soy sauce, vinegar, sesame oil, and black pepper. Toss well and cook for another 1-2 minutes until evenly coated.', 6, 37),
        (263, 'Garnish with sesame seeds and serve immediately.', 7, 37),
        (264, 'Preheat the oven to 400 degrees. Pat dry salmon fillets and place skin-side down on a lined quarter sheet baking pan.', 1, 38),
        (265, 'In a small mixing bowl, stir to combine olive oil, lemon juice, dill, oregano, garlic, salt, and pepper. Brush or pour the marinade over the salmon and let it sit while the oven is preheating.', 2, 38),
        (266, 'Bake for 15 minutes. Let rest for 5 minutes, then serve with an extra squeeze of lemon juice on top, if desired.
', 3, 38),
        (267, 'Note: Leftover salmon will keep in the refrigerator for up to 3-4 days when stored in an airtight container. Allow the fish to cool to room temperature before placing in the refrigerator.', 4, 38),
        (268, 'Bring a medium pot of salted water to a boil. Add pasta and cook until al dente, about 8-10 minutes or according to package instructions.', 1, 39),
        (269, 'Drain and rinse pasta under cold water to stop the cooking process and to cool the pasta down.', 2, 39),
        (270, 'Transfer the pasta to a large mixing bowl or serving bowl. If not assembling the salad immediately, add some olive oil and toss together to prevent the pasta from sticking together. Otherwise, add remaining ingredients.', 3, 39),
        (271, 'In a small mixing bowl, combine Greek salad dressing and yogurt and stir until smooth. Pour the dressing on top, and toss to combine.', 4, 39),
        (272, 'You can serve the pasta salad immediately, or cover the bowl tightly with plastic cling wrap and refrigerate for at least 2 hours.', 5, 39),
        (273, 'This will allow all the flavours to infuse into each other more. When ready to serve, give the salad a good toss and add a little more dressing, if desired.', 6, 39),
        (274, 'Prepare the marinade. Add all of the ingredients for the chicken souvlaki marinade into a large ziploc bag. Press the marinade around to combine. ', 1, 40),
        (275, ' Add in the chopped chicken, and press the air out of the bag and seal tightly. Press the marinade around the chicken to coat. Place in the fridge to marinate at least 1 minutes or overnight.', 2, 40),
        (276, 'Prepare the tzatziki sauce.  Grate the cucumber and drain through a cheesecloth, fine mesh sieve or using your hands. Transfer drained cucumber to a medium bowl. ', 3, 40),
        (277, 'Add the yogurt, garlic, olive oil, lemon juice, dill, salt and pepper. Stir to combine. Refrigerate for at least 1 hour before serving to let the flavours infuse into the yogurt.
', 4, 40),
        (278, 'Prepare the toppings. In a medium bowl, combine the toppings and toss together. ', 5, 40),
        (279, 'Grill the chicken. You can thread the chicken onto skewers to grill, or grill the individual pieces. Lightly brush olive oil over grill pan.', 6, 40),
        (280, 'Heat the grill over medium high heat for about 5 minutes, until sizzling hot. Cook the chicken for 7 minutes on each side, or until its internal temperature reaches 165 F (75 C).', 7, 40),
        (281, 'Assemble the gyros. Warm the pitas on the grill, about 1-2 minutes per side. Then, on the centre each pita bread, add a few spoonfuls of the salad toppings in a line down the middle. ', 8, 40),
        (282, 'Top with grilled souvlaki chicken, and a generous scoop of tzatziki sauce. Fold the pita up and enjoy. You can also wrap it in parchment paper and twist the bottom to keep the ingredients inside.', 9, 40),
        (284, 'In a large mixing bowl, add potatoes, olive oil, garlic, 2 tablespoons lemon juice, Italian seasoning, salt and pepper, and toss to combine until evenly coated.', 2, 41),
        (285, 'Transfer to a quarter baking sheet and spread the potatoes out evenly into a single layer.', 3, 41),
        (286, 'Roast for 35-40 minutes, until golden brown and fork tender (fork inserted easily comes out).', 4, 41),
        (287, 'Remove from oven and serve immediately on a plate. Drizzle with the remaining 1 tablespoon lemon juice over top and toss to combine.', 5, 41);